### ISSUE TITLE
Request body validations using Newtype

### ISSUE THREAD

**Issue by ShubhranshuSanjeev** [juspay/superposition#118]
- [x] #142
- [x] #143
- [x] #144

**Comment by pratikmishra356** [comment]
Validation for Context (write Apis) 

1. **put ("")  (create or update)** -> validate does  request body contains malformed conditions
                      validate does  request body contains empty overrides
                      
2. **update overrides** -> need to validate all the things as in put request and also we should not create the new one, since this is update overrides only

3. **move**  ->. it accepts condition and contexts ids -> we need to validate the conditions either it should empty or valid jsonlogic 

4. **put ( bulk operations )** -> we accept putreq and move req type , so will have to perform the same validation as in 1 and 3

**Comment by pratikmishra356** [comment]
Validation for Default-Config key

1. create or update -> all kinds of validation already present , question is do we need to check overrides when we are trying to update schema of any default config key

2. Delete Api -> validation already present - we are not allowing deletion of key if it is being used in any overrides

**Comment by pratikmishra356** [comment]
**Validation for Default-Config key**

We dont have different api for create and update

1. **create or update** -> currently we dont have restriction on dimension name , 
                                      should we validate schema on the existing conditions containing same dimension ?
                                      we are not enforcing priority value uniqueness
2. **We dont have delete dimension api**

**Comment by pratikmishra356** [comment]
Validation for Experiment Apis

1. **create** -> we are not validating override emptiness and experiment name emptiness

**Comment by pratikmishra356** [comment]
**Validation for Function Apis**
1. **create** -> validate function name

**Comment by pratikmishra356** [comment]
For String type validation we can follow the below approach : 
Create Newtype , for example DimensionName(String), ExperimentName(String), FunctionName(String)
Next, define fn new implementation for each types like
```
impl DimensionName {
    pub fn new(raw_email: &str) -> Result<Self, String> {
        if raw_email.to_owned().len() > 3 {
            Ok(Self(lower))
        } else {
            Err("Invalid Dimension Name minimum length 4".to_string())
        }
    }

```

also implement FromStr trait for each NewType
```
impl FromStr for DimensionName {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, String> {
        DimensionName::new(s)
    }
}
```

Then add a generic deserialize function 
```
fn deserialize_string<'de, T, D>(deserializer: D) -> Result<T, D::Error>
where
    T: TryFrom<String>,
    T::Error: Display,
    D: Deserializer<'de>,
{
    let name: String = Deserialize::deserialize(deserializer)?;
    T::try_from(name).map_err( |op| de::Error::custom(op.to_string()))
}
```

Add this in the request body type as custom deserialize option 
```
#[derive(Debug, Deserialize)]
pub struct CreateReq {
    #[serde(deserialize_with = "deserialize_string")]
    pub dimension: DimensionName,
    pub priority: u16,
    pub schema: Value,
    #[serde(default, deserialize_with = "deserialize_option")]
    pub function_name: Option<Value>,
}
```
We can follow similar approach for Overrides to check empty map , number data type like ramp , priority etc

Any other suggestions ?

**Comment by pratikmishra356** [comment]
Update on the above Approach , its more clean we just have to define tryfrom Trait where we can add he data validation as needed: 
We can declare newtype as below
`#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, AsRef, Deref, Deserialize)]
#[serde(try_from = "String")]
pub struct DimensionName(String);`
In this we will not have to include the below line while declaring any struct where we will use newtype
`#[serde(deserialize_with = "deserialize_string")]    // this is not required`

**Comment by pratikmishra356** [comment]
**Validation of Dimension and Default Config's schema**

We have custom type where user can define types using json-schema, 
so we should remove the jsonschema validation for Default Config and 
for Dimension will have to allow more types in the current jsonschema restriction like remove the pattern as required field if string , include array of numbers etc
