### ISSUE TITLE
Context creation without operator.

### ISSUE THREAD

**Issue by mahatoankitkumar** [juspay/superposition#132]
![Screenshot 2024-06-21 at 3 36 22 PM](https://github.com/juspay/superposition/assets/79959102/cb4c3630-4322-47fd-bd33-e85abc96fa61)

**Comment by ShubhranshuSanjeev** [comment]
@mahatoankitkumar , @pratikmishra356 already assigned to fix this under the `request validation issue`, you can close this issue.
