### ISSUE TITLE
Docker Compose Sample App doesnt have a Arm Build ? 

### ISSUE THREAD

**Issue by jalotra** [juspay/superposition#232]
![image](https://github.com/user-attachments/assets/963e2e0f-0ae5-4b6d-9bd1-ce78dba2309b)

**Comment by Datron** [comment]
Hi @jalotra, the [build](https://github.com/juspay/superposition/actions/runs/10751478491/job/29818785894) is currently in progress, arm takes a bit longer than the x86_64 image. Try again after a while. Sorry about the delay

**Comment by Datron** [comment]
Hi @jalotra , we're still facing a few issues, for the time being you can use this docker image
```
docker run -d -p 8081:9090 -p 8080:8080 datron1/superposition-demo-app:0.55.0
```

**Comment by jalotra** [comment]
okay

**Comment by Datron** [comment]
@jalotra this is fixed, you can use the latest docker image
